services:
  - type: web
    plan: free
    name: mini_trello
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mini_trello.asgi:application -k uvicorn.workers.UvicornWorker'
    # envVars:
    #   - key: SECRET_KEY
    #     generateValue: true
    #   - key: WEB_CONCURRENCY
    #     value: 4